### PR TITLE
onCodeSuccess / onCodeFail / correctCode / center Error Text

### PR DESCRIPTION
**Pull request by Saifallak**

### CODE REVIEW

**Comment by Saifallak** [comment]
Added on CodeSuccess and onCodefail ,, and you must provide correct pin

hint :

do not enter correct pin ,, and you can use onEnteredPin =(the same as)= onCodeFail

**Comment by awazgyawali** [comment]
Looks good, but can you please add a change log message to the change log file.

Also please mention "Breaking changes" as it will affect the working behaviour.

**Comment by Saifallak** [comment]
done @awazgyawali

**Review by awazgyawali — APPROVED** [review]
LGTM

**Pull request merged**
