### PR TITLE
Add optional letters on the bottom of buttons

### LINKED ISSUE #7: Add letters on pin buttons for easier memorization
Hi, it seems some users are used to having letters on the buttons and use them to memorize theirs pins.

Would it be possible to include this feature? I have a working implementation that I would like to upstream, but I think it would still needs some changes.

### PR DESCRIPTION
**Pull request by Dshosev**
Introduce the new showLetters field for PinCode, wich defaults to false.

Switch the old IconButton widgets with MaterialButton for ink-splash.

Make the shape of MaterialButton rounded with a bit of padding.

Add the spacer (SizedBox) and the Text for letters as List (workaround).
This could be changed to use spread-operators in the future.
At the moment spread-operators are not in stable channel.

Swap the empty IconButton on the "bottom-left" with empty Expanded.

Add the new introduced option to the example.

Resolves #7

### CODE REVIEW

**Comment by awazgyawali** [comment]
Looks Good To Me.

**Comment by Dshosev** [comment]
There are some issues with the .gitignore file, but maybe i will look into this in a future commit.

EDIT: sry, accidentally closed :/

**Comment by Dshosev** [comment]
@awazgyawali Are you reviewing the PR or do you want to merge it?

**Comment by awazgyawali** [comment]
Sorry, I forgot about it. I Will update on pub tonight.

**Pull request merged**
